In [ ]:
pip install pandas mysql-connector-python sqlalchemy

Requirement already satisfied: pandas in c:\users\lenovo\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: mysql-connector-python in c:\users\lenovo\anaconda3\lib\site-packages (9.7.0)
Requirement already satisfied: sqlalchemy in c:\users\lenovo\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\lenovo\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd
import mysql.connector
from sqlalchemy import create_engine

In [50]:

from sqlalchemy import create_engine

engine = create_engine(
    "mysql+mysqlconnector://root:mysql@localhost:3307/hr"
)

engine

Engine(mysql+mysqlconnector://root:***@localhost:3307/hr)

In [51]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT DATABASE();"))
    print(result.fetchone())

('hr',)

In [5]:
import os

print(os.getcwd())

C:\Users\LENOVO

In [6]:
import os

print(os.listdir())

['.anaconda', '.arduinoIDE', '.cache', '.conda', '.condarc', '.continuum', '.gitconfig', '.idlerc', '.ipynb_checkpoints', '.ipython', '.jupyter', '.keras', '.lesshst', '.matplotlib', '.ms-ad', '.vscode', '3D Objects', 'anaconda3', 'app.py', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'CrossDevice', 'Desktop', 'Documents', 'Downloads', 'eda_US.ipynb', 'etl.ipynb', 'Favorites', 'index.html', 'IntelGraphicsProfiles', 'Links', 'Local Settings', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{65bb5eac-db0c-11f0-a3fb-841b77a1b6ce}.TxR.0.regtrans-ms', 'NTUSER.DAT{65bb5eac-db0c-11f0-a3fb-841b77a1b6ce}.TxR.1.regtrans-ms', 'NTUSER.DAT{65bb5eac-db0c-11f0-a3fb-841b77a1b6ce}.TxR.2.regtrans-ms', 'NTUSER.DAT{65bb5eac-db0c-11f0-a3fb-841b77a1b6ce}.TxR.blf', 'NTUSER.DAT{65bb5ead-db0c-11f0-a3fb-841b77a1b6ce}.TM.blf', 'NTUSER.DAT{65bb5ead-db0c-11f0-a3fb-841b77a1b6ce}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{65bb5ead-db0c-11f0-a3fb-841b77a1b6ce}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'PrintHood', 'project', 'Recent', 'reg', 'requirements.txt', 'Saved Games', 'Searches', 'SendTo', 'send_otp.py', 'Start Menu', 'Templates', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled2.ipynb', 'upload.html', 'uploads', 'verify_otp.html', 'Videos']

In [7]:
os.getcwd()

'C:\\Users\\LENOVO'

In [54]:
import pandas as pd

df = pd.read_csv(r"C:\Users\LENOVO\OneDrive\Documents\Desktop\assignment\customers.csv")

df.head()

,CustomerID,CustomerName,City,Email,Age,JoinDate,TotalPurchase
0,1,Amit Sharma,Delhi,amit@gmail.com,28.0,1/10/2025,12500.0
1,2,Priya Rao,Chennai,priya@gmail.com,34.0,1/15/2025,22000.0
2,3,Rahul Verma,Mumbai,rahul@gmail.com,41.0,2/2/2025,18500.0
3,4,Sneha Iyer,Bengaluru,sneha@gmail.com,29.0,2/12/2025,9800.0
4,5,Kiran Kumar,Hyderabad,kiran@gmail.com,37.0,3/5/2025,31000.0

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CustomerID     12 non-null     int64
 1   CustomerName   12 non-null     object
 2   City           12 non-null     object
 3   Email          12 non-null     object
 4   Age            11 non-null     float64
 5   JoinDate       12 non-null     object
 6   TotalPurchase  11 non-null     float64
dtypes: float64(2), int64(1), object(4)
memory usage: 804.0+ bytes

In [56]:
df.describe()

       CustomerID        Age  TotalPurchase
count   12.000000  11.000000      11.000000
mean     5.583333  32.090909   17181.818182
std      3.232177   5.243177    7712.433881
min      1.000000  26.000000    7600.000000
25%      2.750000  27.500000   11200.000000
50%      5.500000  31.000000   15400.000000
75%      8.250000  35.500000   22000.000000
max     10.000000  41.000000   31000.000000

In [57]:
df.isnull().sum()

CustomerID       0
CustomerName     0
City             0
Email            0
Age              1
JoinDate         0
TotalPurchase    1
dtype: int64

In [59]:
df.fillna({
    'City':'Unknown',
    'Email':'Not Available',
    'Age':df['Age'].mean(),
    'TotalPurchase':0
}, inplace=True)

In [61]:
df.drop_duplicates(inplace=True)
df

,CustomerID,CustomerName,City,Email,Age,JoinDate,TotalPurchase
0,1,Amit Sharma,Delhi,amit@gmail.com,28.000000,1/10/2025,12500.0
1,2,Priya Rao,Chennai,priya@gmail.com,34.000000,1/15/2025,22000.0
2,3,Rahul Verma,Mumbai,rahul@gmail.com,41.000000,2/2/2025,18500.0
3,4,Sneha Iyer,Bengaluru,sneha@gmail.com,29.000000,2/12/2025,9800.0
4,5,Kiran Kumar,Hyderabad,kiran@gmail.com,37.000000,3/5/2025,31000.0
5,6,Anjali Gupta,Pune,anjali@gmail.com,26.000000,3/15/2025,7600.0
6,7,Vikram Singh,Delhi,vikram@gmail.com,32.090909,4/1/2025,0.0
7,8,Neha Patel,Ahmedabad,neha@gmail.com,31.000000,4/10/2025,15400.0
8,9,Arjun Reddy,Chennai,arjun@gmail.com,39.000000,5/2/2025,27800.0
9,10,Meera Nair,Kochi,meera@gmail.com,27.000000,5/18/2025,11200.0

In [22]:
df.shape

(10, 7)

In [62]:

df['JoinDate'] = pd.to_datetime(df['JoinDate'])

In [63]:
total_purchase = df['TotalPurchase'].sum()

print("Total Purchase:", total_purchase)

Total Purchase: 155800.0

In [64]:

df.to_sql(
    name="customer_load",
    con=engine,
    if_exists="replace",
    index=False
)



print("ETL Load Completed")

ETL Load Completed

In [65]:

pd.read_sql("SELECT * FROM customer_load", con=engine)

,CustomerID,CustomerName,City,Email,Age,JoinDate,TotalPurchase
0,1,Amit Sharma,Delhi,amit@gmail.com,28.000000,2025-01-10,12500.0
1,2,Priya Rao,Chennai,priya@gmail.com,34.000000,2025-01-15,22000.0
2,3,Rahul Verma,Mumbai,rahul@gmail.com,41.000000,2025-02-02,18500.0
3,4,Sneha Iyer,Bengaluru,sneha@gmail.com,29.000000,2025-02-12,9800.0
4,5,Kiran Kumar,Hyderabad,kiran@gmail.com,37.000000,2025-03-05,31000.0
5,6,Anjali Gupta,Pune,anjali@gmail.com,26.000000,2025-03-15,7600.0
6,7,Vikram Singh,Delhi,vikram@gmail.com,32.090909,2025-04-01,0.0
7,8,Neha Patel,Ahmedabad,neha@gmail.com,31.000000,2025-04-10,15400.0
8,9,Arjun Reddy,Chennai,arjun@gmail.com,39.000000,2025-05-02,27800.0
9,10,Meera Nair,Kochi,meera@gmail.com,27.000000,2025-05-18,11200.0

In [68]:
#4.Find top customers by purchase

pd.read_sql("SELECT CustomerID,CustomerName,TotalPurchase FROM Customers ORDER BY TotalPurchase DESC LIMIT 5;", con=engine)

   CustomerID CustomerName  TotalPurchase
0           5  Kiran Kumar        31000.0
1           9  Arjun Reddy        27800.0
2           2    Priya Rao        22000.0
3           2    Priya Rao        22000.0
4           3  Rahul Verma        18500.0

In [69]:
#5.Analyze city-wise revenue
pd.read_sql("SELECT City,SUM(TotalPurchase) AS Revenue FROM Customers GROUP BY City ORDER BY Revenue DESC;", con=engine)

        City  Revenue
0    Chennai  71800.0
1  Hyderabad  31000.0
2      Kochi  22400.0
3     Mumbai  18500.0
4  Ahmedabad  15400.0
5      Delhi  12500.0
6  Bengaluru   9800.0
7       Pune   7600.0

In [70]:
#6.Rank customers using window functions

pd.read_sql("SELECT CustomerID,CustomerName,TotalPurchase,RANK() OVER (ORDER BY TotalPurchase DESC) AS CustomerRank FROM Customers;", con=engine)

    CustomerID  CustomerName  TotalPurchase  CustomerRank
0            5   Kiran Kumar        31000.0             1
1            9   Arjun Reddy        27800.0             2
2            2     Priya Rao        22000.0             3
3            2     Priya Rao        22000.0             3
4            3   Rahul Verma        18500.0             5
5            8    Neha Patel        15400.0             6
6            1   Amit Sharma        12500.0             7
7           10    Meera Nair        11200.0             8
8           10    Meera Nair        11200.0             8
9            4    Sneha Iyer         9800.0            10
10           6  Anjali Gupta         7600.0            11
11           7  Vikram Singh            NaN            12

In [77]:
#7. Total Customers
pd.read_sql("""
SELECT MONTH(JoinDate) AS Month,
       COUNT(*) AS NewCustomers
FROM Customers
GROUP BY MONTH(JoinDate)
ORDER BY Month
""", engine)

  Month  NewCustomers
0  None            12

In [72]:
#8. City-wise Customer Count
pd.read_sql("SELECT City,COUNT(*) AS CustomerCount FROM Customers GROUP BY City;", con=engine)

        City  CustomerCount
0      Delhi              2
1    Chennai              3
2     Mumbai              1
3  Bengaluru              1
4  Hyderabad              1
5       Pune              1
6  Ahmedabad              1
7      Kochi              2

In [73]:
#9. Fetch Above Average Customers Information
pd.read_sql("SELECT * FROM Customers WHERE TotalPurchase > ( SELECT AVG(TotalPurchase) FROM Customers );", con=engine)

,CustomerID,CustomerName,City,Email,Age,JoinDate,TotalPurchase
0,2,Priya Rao,Chennai,priya@gmail.com,34.0,1/15/2025,22000.0
1,3,Rahul Verma,Mumbai,rahul@gmail.com,41.0,2/2/2025,18500.0
2,5,Kiran Kumar,Hyderabad,kiran@gmail.com,37.0,3/5/2025,31000.0
3,9,Arjun Reddy,Chennai,arjun@gmail.com,39.0,5/2/2025,27800.0
4,2,Priya Rao,Chennai,priya@gmail.com,34.0,1/15/2025,22000.0

In [75]:
#10. find Customer Acquisition Trend  - month wise
pd.read_sql("SELECT DATE_FORMAT(JoinDate,'%Y-%m') AS Month,COUNT(*) AS NewCustomers FROM Customers GROUP BY Month ORDER BY Month;", con=engine)

  Month  NewCustomers
0  None            12

In [76]:
#year wise
pd.read_sql("SELECT YEAR(JoinDate) AS Year, COUNT(*) AS NewCustomers FROM Customers GROUP BY Year ORDER BY Year;", con=engine)

   Year  NewCustomers
0  None            12